import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.scss";
import RootLayout from "./layout";
import LightGallery from "lightgallery/react";
import "lightgallery/css/lightgallery.css";
import "lightgallery/css/lg-zoom.css";
import "lightgallery/css/lg-thumbnail.css";
import lgThumbnail from "lightgallery/plugins/thumbnail";
import lgZoom from "lightgallery/plugins/zoom";

import image1 from "@/assets/Images/OIP.jpg";
import image2 from "@/assets/Images/R.jpg";

const inter = Inter({ subsets: ["latin"] });

export default function Gallery() {
  return (
    <RootLayout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className={styles["main-gallery"]}>
          <LightGallery
            speed={500}
            plugins={[lgThumbnail, lgZoom]}
            thumbnail={true}
          >
            <a href={image1.src}>
              <img alt="img1" src={image1.src} />
            </a>
            <a href={image2.src}>
              <img alt="img2" src={image2.src} />
            </a>
            <a href={image1.src}>
              <img alt="img1" src={image1.src} />
            </a>
            <a href={image2.src}>
              <img alt="img2" src={image2.src} />
            </a>
            <a href={image1.src}>
              <img alt="img1" src={image1.src} />
            </a>
            <a href={image2.src}>
              <img alt="img2" src={image2.src} />
            </a>
            <a href={image1.src}>
              <img alt="img1" src={image1.src} />
            </a>
            <a href={image2.src}>
              <img alt="img2" src={image2.src} />
            </a>
          </LightGallery>
        </div>
      </main>
    </RootLayout>
  );
}
