import styles from "@/styles/Home.module.scss";
import { Inter } from "next/font/google";
import Head from "next/head";
import RootLayout from "./layout";
const inter = Inter({ subsets: ["latin"] });

export default function Menu() {
  return (
    <RootLayout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {/* <iframe
          src="https://flowpaper.com/flipbook/https://icseindia.org/document/sample.pdf"
          width="70%"
          height="800"
          style={{ border: "none" }}
          allowFullScreen
        ></iframe> */}
      </main>
    </RootLayout>
  );
}
